/* ═══════════════════════════════════════════════════════════════════════
   dp2-daten.js · v1540 · Die Inhalte der DealPilot-Seite
   ───────────────────────────────────────────────────────────────────────
   MODULE und STORIES sind UNVERAENDERT aus der bisherigen Landing
   uebernommen (frontend/landing/index.html, Z.1516 und Z.1553) - per
   Skript herauskopiert, nicht abgetippt. Damit ist ausgeschlossen, dass
   beim Neubau ein Modul oder eine Geschichte verloren geht oder sich ein
   Tippfehler einschleicht.
   19 Module, 16 Geschichten - beim Uebernehmen gezaehlt.
   ═══════════════════════════════════════════════════════════════════════ */

window.DP_MODULE = [
    {i:'<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2 3 14h7l-1 8 11-13h-8l1-7z"/></svg>',t:'Boarding',s:'Schnellbewertung mit den wichtigsten Zahlen.',b:['Live-Berechnung beim Tippen','BMR, Faktor, Cashflow, LTV','\u00dcbernahme in Vollberechnung']},
    {i:'\u25A4',t:'PDF-Import',s:'Expos\u00e9 rein \u2014 Felder gef\u00fcllt.',b:['KI-Extraktion der Eckdaten','Bilder aus dem Expos\u00e9','Spart das Abtippen']},
    {i:'\u2302',t:'Objekt & Lage',s:'Grunddaten, Fotos, Lageparameter.',b:['Bis zu 30 Objektfotos','Makro/Mikro/Demografie','AfA f\u00fcr Geb\u00e4udeanteil']},
    {i:'\u20AC',t:'Investition',s:'Kaufpreis, Nebenkosten, Sanierung.',b:['Erwerbsnebenkosten komplett','Sanierung nach 8 Gewerken','15%-Regel live']},
    {i:'\u2197',t:'Miete & Markt',s:'Mietstruktur und Markt-Vergleich.',b:['Mietpreis-Analyse \u20ac/m\u00b2','KI-Marktmieten-Recherche','Staffelmiete']},
    {i:'\u25A6',t:'Werbungskosten',s:'Fertig f\u00fcrs Finanzamt.',b:['Detaillierter Werbungskosten-Rechner','BMF-Rechner integriert','Arbeitshilfe wird direkt ausgef\u00fcllt']},
    {i:'\u25A5',t:'Finanzierung',s:'Annuit\u00e4t, Anschluss, Bausparen.',b:['Live-Marktzinsen','Tilgungsplan + Anschluss','Bausparvertrag-Zyklus']},
    {i:'<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><line x1="4" y1="21" x2="4" y2="14"/><line x1="4" y1="10" x2="4" y2="3"/><line x1="12" y1="21" x2="12" y2="12"/><line x1="12" y1="8" x2="12" y2="3"/><line x1="20" y1="21" x2="20" y2="16"/><line x1="20" y1="12" x2="20" y2="3"/><line x1="1" y1="14" x2="7" y2="14"/><line x1="9" y1="8" x2="15" y2="8"/><line x1="17" y1="16" x2="23" y2="16"/></svg>',t:'Bewirtschaftung',s:'Umlagef\u00e4hig getrennt.',b:['Hausgeld, Verwaltung, R\u00fccklage','Detail oder %-NKM','Mietausfall-Risiko']},
    {i:'<svg viewBox=\"0 0 24 24\" width=\"19\" height=\"19\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 14v-3a9 9 0 0 1 18 0v3\"/><path d=\"M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3z\"/><path d=\"M3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z\"/></svg>',t:'Co-Pilot (KI)',s:'Co-Pilot mit Web-Recherche.',b:['St\u00e4rken, Risiken, Fit','Verhandlungsempfehlung','Kaufpreis-Offerte als Text']},
    {i:'\u25CE',t:'Investor Deal Score',s:'0\u2013100 aus 24 KPIs.',b:['5 Bereiche gewichtet','LTV/DSCR-Bonus','Ampel ohne KI']},
    {i:'\u2926',t:'Bankexport',s:'Bankf\u00e4hige Unterlagen in Sekunden.',b:['Investment-Case-PDF','Logo & Adresse im PDF','Excel/CSV (25 Spalten)']},
    {i:'\u25A9',t:'Portfolio',s:'Alle Objekte in einer \u00dcbersicht.',b:['Suchbare Tabelle','Portfolio-Cockpit','JSON-Export']},
    {i:'<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"/></svg>',t:'Auto-Save & Cloud',s:'Immer aktuell, immer sicher.',b:['Auto-Save','Cloud-Sync','Lokal-Modus m\u00f6glich']},
    {i:'<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><line x1="19" y1="5" x2="5" y2="19"/><circle cx="6.5" cy="6.5" r="2.5"/><circle cx="17.5" cy="17.5" r="2.5"/></svg>',t:'Steuer & AfA',s:'Vom Modell bis zur Ersparnis/Jahr.',b:['Linear, degressiv, \u00a7 7b','BMF-Rechner','Grenzsteuersatz 2026']},
    {i:'\u25D0',t:'Marktdaten',s:'Live-Daten statt Bauchgef\u00fchl.',b:['DealPilot Markteinsch\u00e4tzung','Bodenrichtwert (BORIS)','Mietspiegel-Vergleich']},
    {i:'<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',t:'Partnernetzwerk',s:'Experten direkt aus der App.',b:['Sachverst\u00e4ndige, Finanzierer, Steuerberater','RND-Gutachten \u00fcber Partner','Anfrage mit einem Klick']},
    {i:'<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a3 3 0 0 1 3 3v6a3 3 0 0 1-6 0V5a3 3 0 0 1 3-3z"/><path d="M19 10v1a7 7 0 0 1-14 0v-1"/><line x1="12" y1="18" x2="12" y2="22"/></svg>',t:'Spracheingabe',s:'Diktieren statt tippen.',b:['Objekt komplett per Sprache erfassen','Live-Mitschrift beim Sprechen','KI ordnet Werte den Feldern zu']},
    {i:'<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>',t:'ImmoMetrica-Anbindung',s:'Inserate direkt \u00fcbernehmen.',b:['Vollintegration mit eigenem Zugang','Objekte mit einem Klick importieren','Portale &amp; Online-Status im Blick']},
    {i:'<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 15l3.5-3.5"/><path d="M20.3 18a9 9 0 1 0-16.6 0"/></svg>',t:'Marktbewertung (AVM)',s:'Professionelle Wertindikation.',b:['Zwei professionelle Bewertungspartner','DealPilot-Markteinsch\u00e4tzung inklusive','Marktwert, Marktmiete, Vergleichspreise']}
  ];

window.DP_STORIES = [
    {n:'01',tag:'// Der Anruf am Donnerstagabend',scene:'„Donnerstag, 19:42 Uhr. Du bist gerade beim Abendessen mit deiner Familie. Dein Bekannter schreibt: Drei-Familien-Haus, Vor-Ort-Termin am Samstag um zehn — und vor dir liegt ein 18-seitiges Exposé."',body:['Du kennst diese Situation. Jeder, der ernsthaft in Immobilien investiert, kennt sie. Du hast 36 Stunden, um zu wissen, ob du Samstag früh in dein Auto steigst und 280 km zur Besichtigung fährst — oder ob du höflich absagst.','Vor DealPilot hieß das: Excel auf, 90 Minuten konzentriert tippen, vier Browsertabs mit Mietspiegel, Zinsrechner, AfA-Hilfe und Bundesbank-Zinsstatistik. Drei Stunden später hast du eine Excel-Datei, der du nicht ganz vertraust, und ein Bauchgefühl.','Mit DealPilot ziehst du das Exposé in den PDF-Import. Die KI extrahiert Kaufpreis, Wohnfläche, Baujahr, Adresse, Miete und Hausgeld — in unter 30 Sekunden. Im Boarding tippst du deine Finanzierungsannahmen. Faktor 18,2 — Bruttomietrendite 5,5 % — Cashflow nach Werbungskosten plus 187 € — LTV 87 %.','Du gehst zurück zum Tisch. Sagst „Ja, gern noch ein Glas". Und am Samstag stehst du rechtzeitig auf dem Hof — mit einem informierten Bauchgefühl, nicht einem blinden.'],pay:'PDF-Import + Boarding · 4 Minuten statt 3 Stunden'},
    {n:'02',tag:'// Die 15-%-Falle',scene:'„Im ersten Jahr: 24.000 € fürs Dach, 12.000 € neue Heizung, 18.000 € drei Bäder. Du freust dich, das alles im ersten Jahr als Werbungskosten absetzen zu können."',body:['Sechs Monate später sitzt dein Steuerberater dir gegenüber und sagt den Satz, den kein Investor hören will: „Das müssen wir aktivieren. Sie sind über der 15-%-Grenze."','Anschaffungsnahe Herstellungskosten. Wenn du in den ersten drei Jahren nach Kauf mehr als 15 % der Gebäude-Anschaffungskosten in Instandsetzung steckst, gelten die Beträge nicht mehr als sofort absetzbare Werbungskosten — sie werden über die Restnutzungsdauer abgeschrieben. Aus 54.000 € sofortigem Werbungskostenabzug werden über 40 Jahre verteilt. Das frisst deinen Cashflow im ersten Jahr — und du hast es schlicht nicht gewusst.','DealPilot kennt diese Falle. Während du Sanierungsbeträge im Investitionsmodul eingibst, läuft im Hintergrund ein Balken, der dir live zeigt: „Du bist bei 11 % deiner Gebäude-AK. Spielraum: 13.400 €." Überschreitest du die Grenze, springt die Anzeige auf Rot.','Ein einziger Hinweis. Ein roter Balken. Und du sparst dir den Termin mit dem Steuerberater, bei dem dir fünfstellige Liquidität durch die Lappen gehen.'],pay:'Live-Balken im Investitionsmodul · Fünfstellige Steuerfalle vermieden'},
    {n:'03',tag:'// Das Bankgespräch',scene:'„Mittwochabend, 21:14 Uhr. Mail von deiner Filialleiterin. Sie braucht den vollständigen Investment-Case bis morgen 9 Uhr — sonst rutscht dein Termin am Freitag aus dem Ressort."',body:['Du hast noch keine einzige Seite formatiert. Banker brauchen strukturierte Unterlagen — nicht eine Excel mit 20 Tabs und drei Farbschemata. Nicht eine handgetippte Word-Datei. Sondern eine ordentlich gegliederte Vorlage, in der die Bank in unter zehn Minuten sieht: Was wird gekauft, was kostet\'s, wie ist es finanziert, wie sieht der Cashflow aus, was passiert am Ende der Zinsbindung — und warum ist das Risiko vertretbar.','DealPilot baut diese Vorlage automatisch. Sobald du alle Module ausgefüllt hast, bekommst du mit einem Klick einen vollständigen Investment-Case: Deckblatt mit Titelfoto und vier Cover-KPIs. Executive Summary mit Cashflow-Szenario heute, Ende Zinsbindung und Anschluss. Eine Seite Objekt &amp; Finanzierungsstruktur. 15-Jahres-Cashflow-Projektion. KI-Analyse als Fließtext. Annahmen und Disclaimer.','Sechs Seiten. Vollständig. Bankfähig. Du klickst, du lädst hoch, du gehst ins Bett. Am Donnerstag 8:53 Uhr versendet. Am Freitag im Termin: die Beraterin hat schon Notizen am Rand. Das ist der Unterschied zwischen einem Kunden, der vorbereitet kommt, und einem, der drei Termine später noch verhandeln muss.'],pay:'Investment-Case mit einem Klick · 6 Seiten bankfähig'},
    {n:'04',tag:'// Die Verhandlung',scene:'„Du hast ein Objekt gefunden, das passt. Der Eigentümer verlangt 485.000 €. Dein Bauchgefühl sagt: zu teuer. Aber wie viel zu teuer? Und mit welcher Begründung verhandelst du, ohne gleich rausgeschmissen zu werden?"',body:['Verhandlung ohne Daten ist Pokern. Verhandlung mit Daten ist Schach. DealPilot rechnet dir aus, welcher Kaufpreis bei deinen Annahmen welche Rendite ergibt. Du siehst sofort: Bei 485.000 € landest du bei 4,2 % Bruttomietrendite und einem Cashflow von minus 87 €. Bei 455.000 € sind es 4,5 % und plus 34 €. Bei 425.000 € sind es 4,8 % und plus 156 €.','Mit dieser Information startest du die KI-Investment-Analyse. Die KI nimmt deine Zahlen, recherchiert die Lage im Web, vergleicht mit ähnlichen Verkäufen und sagt dir: Erstangebot 410.000 € — Zielpreis 430.000 € — Schmerzgrenze 455.000 €. Plus eine fertige Kaufpreis-Offerte als Text, formell gehalten, mit Begründungen für die E-Mail an den Verkäufer. Plus fünf Argumente für die Bank, warum dein Angebot vertretbar ist.','Du verhandelst nicht mehr aus dem Bauch. Du verhandelst mit Zahlen, die du belegen kannst. Verkäufer respektieren begründete Argumente. Du fängst die Verhandlung mit drei Schritten Vorsprung an.'],pay:'KI-Verhandlungsempfehlung · konkrete Euro-Beträge'},
    {n:'05',tag:'// Ende der Zinsbindung',scene:'„Zehn Jahre nach Kauf. Du sitzt mit deinem Berater zusammen. Die Bank schlägt 5,2 % für die Anschlussfinanzierung vor — du hattest 2,1 % bei Abschluss. Du fragst dich: Hält mein Cashflow das aus? Oder muss ich verkaufen?"',body:['Das ist die wichtigste Frage, die die wenigsten Investoren rechtzeitig stellen. Wer 2015 mit 1,8 % gekauft hat, wer 2017 mit 1,4 % refinanziert hat, wer 2019 das Maximaltilgungspaket gewählt hat — der kann 2026 in eine Anschlussfinanzierung rutschen, bei der die monatliche Rate sich verdoppelt. Wer das nicht durchgerechnet hat, schaut blass auf die Zahlen.','DealPilot rechnet diesen Stresstest von Anfang an mit. Du gibst eine Annahme für den Anschlusszins ein — etwa „aktueller Marktzins plus 1,5 %" — und siehst sofort: Wie hoch ist die neue Rate? Wie verändert sich der Cashflow? Trägt die aktuelle Miete die Belastung? Rutscht das Objekt in den negativen Bereich?','Wenn der Stresstest zeigt, dass dein Objekt eine Anschlussfinanzierung bei 5 oder 6 % nicht überlebt: weißt du es zehn Jahre vorher. Du hast Zeit zu reagieren — Sondertilgung erhöhen, Miete anpassen, Bausparvertrag einrichten, notfalls vor der Anschlussfinanzierung verkaufen. Das ist kein Pessimismus. Das ist Risikomanagement, das die Bank von dir erwartet.'],pay:'Anschluss-Stresstest · Tilgungsplan über volle Laufzeit'},
    {n:'06',tag:'// 24 KPIs. Eine Zahl.',scene:'„Du hast drei Objekte zur Auswahl. Alle drei sehen auf den ersten Blick okay aus. Alle drei haben Stärken, alle drei haben Risiken. Aber welches ist objektiv das beste?"',body:['Hier kommt der Investor Deal Score 2.0 ins Spiel. Eine Bewertung von 0 bis 100, basierend auf 24 Einzelkennzahlen aus fünf Bereichen — Rendite, Cashflow, Finanzierung, Risiko und Potenzial. Jede Kennzahl mit Schwellenwerten kalibriert aus der Praxis institutioneller Investoren. Jede gibt Punkte. Die Punkte werden mit Bereichs-Gewichten verrechnet. Heraus kommt: eine Zahl, die du vergleichen kannst.','Objekt A: 73 Punkte. Stärken: starke Rendite, niedriger Kaufpreis-pro-Quadratmeter, gute Lage. Schwäche: kritischer DSCR (1,05). Objekt B: 67 Punkte. Stärken: Top-Lage, niedriger Leerstand. Schwäche: hoher Kaufpreis-Faktor, magere Rendite. Objekt C: 81 Punkte. Stärken: ausgewogen über alle Bereiche, gute Finanzierungsstruktur, klares Wertsteigerungs-Potenzial.','Klare Sache — bis du das Kleingedruckte liest. Objekt A punktet genau in dem Bereich, der dir als Cashflow-Investor wichtig ist. Du gewichtest neu. Live-Anzeige aktualisiert sich. Objekt A: 78. Objekt C: 79. Hart umkämpft — aber jetzt begründet.'],pay:'Deal Score 2.0 · 24 KPIs · Anpassbare Gewichte'},
    {n:'07',tag:'// Die Folgefinanzierung',scene:'„Du betrittst die Bankfiliale für eine Folgefinanzierung. Die Beraterin reicht dir Kaffee und fragt: ‚Wie sieht Ihr Bestand derzeit aus?\' Du beginnst, in deinem Kopf zu rechnen — wann hattest du das letzte Mal alle Cashflows zusammengezählt?"',body:['Wer mehr als zwei Objekte besitzt, kennt diese Frage. Und wer sie ein paarmal bekommen hat, weiß, wie peinlich es ist, wenn man die Antwort schuldig bleibt — oder schlimmer: wenn man eine Antwort gibt und sie sich später als falsch herausstellt.','DealPilot kennt dein Portfolio. In der Portfolio-Übersicht liegen alle deine Objekte als suchbare, sortierbare Tabelle — Kürzel, Adresse, Kaufpreis, Gesamtinvestition, Rendite, DSCR, LTV, Cashflow, Deal Score. Eine Sidebar zeigt dir auf einen Blick die Highlights jedes Objekts.','Und das Track-Record-PDF: Ein Bestandsnachweis, den du der Bank in die Hand drückst. Jedes Objekt mit Foto, Kaufpreis, Cashflow, Rendite und Deal Score auf einer kompakten Seite. Plus Portfolio-Aggregate. Statt nervös im Kopf zu rechnen, sagst du: „Hier ist mein aktueller Track-Record." Die Beraterin blättert. Lächelt. Du hast die Folgefinanzierung schon zur Hälfte gewonnen.'],pay:'Portfolio-Übersicht · Track-Record für die Bank'},
    {n:'08',tag:'// Live-Marktzinsen',scene:'„Du sprichst mit deiner Hausbank über die Konditionen. Sie nennt dir 4,1 %. Klingt fair? Oder klingt nur fair, weil du keinen Vergleich hast?"',body:['DealPilot zeigt dir direkt im Finanzierungs-Tab die aktuellen Effektivzinsen für Wohnungsbaukredite — variabel, 1–5 Jahre, 5–10 Jahre, über 10 Jahre. Daten kommen aus der ECB-MFI-Statistik der Bundesbank, monatlich aktualisiert. Mit Stand-Datum, mit Quelle, ohne Hokuspokus.','Plus: Vergleichslinks zu Interhyp, Dr. Klein und Baufi24 — damit du deine eigene Konditionen-Anfrage direkt machen kannst und siehst, ob die 4,1 % deiner Hausbank am Markt liegen oder ob du nochmal verhandeln solltest.','Eine kleine Funktion. Aber eine, die dich pro Finanzierung mehrere hundert Euro pro Jahr kosten kann, wenn du sie nicht hast. Über zehn Jahre Zinsbindung summiert sich das schnell zu fünfstelligen Beträgen.'],pay:'Live-Marktzinsen Bundesbank · ECB-MFI-Statistik'},
    {n:'09',tag:'// Das Steuergespräch',scene:'„Mai. Du sitzt beim Steuerberater. Er fragt: ‚Können Sie mir die Werbungskosten für Ihr Mehrfamilienhaus aufschlüsseln? AfA, Schuldzinsen, Bewirtschaftung, Sanierung — alles?\'"',body:['Du beginnst, in deinen Ordnern zu kramen. Belege suchen, Excel öffnen, Schuldzinsen aus dem Tilgungsplan abschreiben, AfA neu berechnen. Eine Stunde Termin, davon 30 Minuten mit dem Aktenkoffer beschäftigt.','DealPilot generiert dir auf Knopfdruck ein Werbungskosten-PDF: Alle Positionen, sortiert und summiert. AfA, Schuldzinsen, Bewirtschaftungskosten, Sanierungskosten, Möblierung, Fahrtkosten — über 15 Jahre projiziert. Mit Tabelle für das aktuelle Jahr, mit Verlaufsdiagramm für die Folgejahre.','Du legst das PDF auf den Tisch. Steuerberater scannt zwei Minuten durch. „Sehr gut. Den Rest übernehme ich." Dein Termin ist 40 Minuten kürzer — und die Beratungsrechnung entsprechend günstiger.'],pay:'Werbungskosten-PDF · Belegübersicht für den Steuerberater'},
    {n:'10',tag:'// Der Bausparvertrag',scene:'„Du finanzierst dein nächstes Objekt mit Tilgungsaussetzung über Bausparvertrag. Klingt clever — niedrige Raten, Steuervorteil. Aber: Reicht die Bausparsumme am Ende wirklich, um das Tilgungsaussetzungsdarlehen abzulösen?"',body:['Das ist die kritische Lücke, die viele Investoren übersehen. Wer Tilgungsaussetzungs-Darlehen mit Bausparverträgen kombiniert, fährt einen Zeitstrahl mit zwei Bewegungen: Das Tilgungsaussetzungsdarlehen wächst nicht, der Bausparvertrag spart langsam an. Wenn die Mindest-Quote bei Zuteilung erreicht ist und die Bausparsumme das Hauptdarlehen exakt deckt — perfekt. Wenn nicht — Lücke. Eine Lücke, die du erst in zehn Jahren bemerkst.','DealPilot bildet den vollen Bausparvertrag-Lebenszyklus ab. Ansparphase, Zuteilungszeitpunkt, Darlehensphase mit dem zugesagten Sollzins. Während du die Werte eingibst, läuft eine Plausibilitätsprüfung im Hintergrund. Wenn die Bausparsumme nicht reicht, warnt die App.','Du gehst nicht mit einem Wunschdenken ins Bankgespräch. Du gehst mit einem durchgerechneten Konzept, das auch in zehn Jahren noch trägt.'],pay:'Bausparvertrag-Lebenszyklus · Plausibilitätsprüfung'},
    {n:'11',tag:'// Die KI-Investment-These',scene:'„Du hast deine Zahlen. Du hast deinen Score. Aber: Was würde ein erfahrener Investment-Manager dazu sagen? Einer, der nicht müde wird, der nicht höflich ist, der dir alles sagt — auch das, was wehtut?"',body:['Mit einem Klick startet die KI-Investment-Analyse. Die KI nimmt alle deine Daten — alle Zahlen, alle Kennzahlen, alle Lage-Selbsteinschätzungen — und schickt sie zusammen mit einer Web-Recherche zur Lage an ChatGPT.','Was du zurückbekommst, ist strukturierte Investment-Bewertung mit echten Argumenten: Gesamtbewertung mit klarem Rating („Sehr attraktiv" bis „Ungeeignet"). Stärken und Risiken jeweils 4–5 nummerierte Punkte, ausführlich begründet mit Bezug auf deine echten Zahlen. Risikoanalyse für Finanzierung, Cashflow-Stabilität, Annahmen-Abhängigkeit. Szenario-Analyse Worst Case (Miete −10 %, Zins +1 %) und Best Case durchgerechnet. Investor-Fit-Einschätzung. Klare Empfehlung „Kaufen" / „Prüfen" / „Nicht kaufen" — mit Begründung.','Plus: eine konkrete Verhandlungsempfehlung mit Erstangebot, Zielpreis, Schmerzgrenze — jeweils mit Euro-Betrag. Plus eine fertige Kaufpreis-Offerte als kopierbarer Text. Plus fünf bis sieben Argumente für die Bank. Ein Berater, der in zwei Minuten liefert, wofür du sonst eine Woche Recherche bräuchtest.'],pay:'KI-Analyse · 9 Output-Sektionen · 1 Credit = 2 Analysen'},
    {n:'12',tag:'// Das Mieter-Gespräch',scene:'„Du hast eine Wohnung neu vermietet. 7,80 € pro Quadratmeter. Klingt vernünftig. Aber: Würde der Markt mehr hergeben? Lässt du gerade Geld liegen?"',body:['Die Mietpreis-Analyse zeigt dir, wie sich deine Miete in € pro Quadratmeter zur lokalen Marktmiete verhält. Sind die 7,80 €/m² in einer Stadt mit Mietspiegel 9,20 €/m² ein Schnäppchen für den Mieter, also Mietsteigerungs-Potenzial? Oder einfach zu niedrig kalkuliert?','Im Investor- und Pro-Plan kommt die KI-Marktmieten-Recherche dazu: Die KI sucht im Web nach aktuellen Vergleichsangeboten in deiner Lage, schätzt eine plausible Mietbandbreite und nennt dir Quellen. So weißt du nicht nur, was der Mietspiegel sagt — sondern was Vermieter tatsächlich aktuell verlangen.','Bei 84 m² und einer realistischen Marktmiete von 9,00 statt 7,80 €/m² sind das 1.200 € mehr Jahresmiete pro Jahr. Über zehn Jahre 12.000 € — bei verkaufsorientierter Bewertung sogar mehr. Aus „klingt vernünftig" wird „auf dem Tisch."'],pay:'Mietpreis-Analyse · KI-Marktmieten-Recherche'},
    {n:'13',tag:'// Power-Pitch · Excel vs. DealPilot',scene:'„Schluss mit Excel-Voodoo."',body:['Vor DealPilot: Drei Tabs offen. Mietspiegel googeln. AfA per Hand. Schuldzinsen aus dem Tilgungsplan abschreiben. Hausgeld vergessen, korrigieren. Mietausfall? Vergessen. Drei Stunden später hast du eine Excel-Datei, der du nicht ganz traust.','Mit DealPilot: PDF reinziehen. Sechs Felder prüfen. Übernehmen. Cashflow steht. Score steht. Investment-Case steht. In der Zeit, in der du vorher den Mietspiegel gegoogelt hast, bist du fertig.','Eine Plattform. Sieben Module. Null Bauchgefühl. Das ist der Unterschied zwischen Hobby und Profi.'],pay:'7 Module verknüpft · keine Excel-Vorlagen mehr'},
    {n:'14',tag:'// Founder-Voice · Warum wir DealPilot gebaut haben',scene:'„Vor drei Jahren saß ich an einem Samstagnachmittag in meinem Büro und rechnete mein siebtes Mehrfamilienhaus durch. Sechs Stunden. Für ein Objekt, das ich am Ende nicht gekauft habe."',body:['Ich bin Immobilien-Sachverständiger. Ich kenne die Zahlen, die zählen. Ich kenne die Stolperfallen. Aber jedes Mal aufs Neue im Excel anfangen, jedes Mal wieder die gleichen Formeln tippen — das ist Zeitverschwendung auf hohem Niveau.','Also habe ich mir mein eigenes Tool gebaut. Erst nur für mich. Dann für meine Beratungskunden. Irgendwann wurde mir klar: andere Investoren brauchen das auch. So entstand DealPilot.','Was du in der App siehst, ist kein theoretisches Modell. Es sind die Module, mit denen ich heute selbst arbeite — und mit denen ich Kunden bei Junker Immobilien durch ihre Investments begleite.'],pay:'— Marcel Junker · Junker Immobilien'},
    {n:'15',tag:'// Power-Pitch · 30 Sekunden zur Wahrheit',scene:'„Sechs Zahlen. Eine Wahrheit."',body:['Kaufpreis. Wohnfläche. Miete. Eigenkapital. Zins. Tilgung. Mehr brauchst du nicht.','Bruttomietrendite, Faktor, monatliche Rate, Cashflow, LTV, Kaufpreis pro Quadratmeter — live, während du tippst. Keine „Berechnen"-Buttons. Kein Warten. Eine Ampel sagt dir auf den ersten Blick: lohnenswert oder Zeitfresser.','Was passt? Übernimm es mit einem Klick in die Vollberechnung. Was nicht passt? Nächstes Exposé. Schlechte Deals in 30 Sekunden aussortieren — das ist der einzige Weg, mit dem du als Privatinvestor je in die Nähe eines Profi-Workflows kommst.'],pay:'Boarding · Live-Berechnung · 30 Sekunden'},
    {n:'16',tag:'// Founder-Voice · Die 15-%-Lektion',scene:'„2019 habe ich mit meinem Steuerberater eine sehr unangenehme Stunde verbracht. Ich hatte gerade ein Objekt gekauft und im ersten Jahr 64.000 € in Sanierung gesteckt — Dach, Heizung, drei Bäder."',body:['Mein Steuerberater hat mich angeschaut und gesagt: „Marcel, Sie sind über der 15-%-Grenze. Wir müssen aktivieren." Aus 64.000 € sofortigem Werbungskosten-Abzug wurde eine Aktivierung über 40 Jahre. Im ersten Jahr ein Liquiditätsverlust im hohen vierstelligen Bereich.','An dem Abend habe ich beschlossen: Das passiert mir nie wieder. Und es passiert auch meinen Beratungskunden nicht. Im Investitionsmodul läuft seitdem ein Live-Balken, der dir bei jeder Sanierungsposition zeigt, wo du stehst. Wenn du über die Grenze gehst, springt die Anzeige auf Rot.','Das ist keine Feature-Erfindung. Das ist eine Lektion aus eigenem Schaden, gegossen in Code, damit niemand anders sie nochmal lernen muss.'],pay:'— Aus eigener Erfahrung in Code gegossen'},
  ];
